version: '3.5'

services:
  selenoid:
    image: aerokube/selenoid:latest
    volumes:
      - "./init/selenoid:/etc/selenoid"
      - "./work/selenoid/video:/opt/selenoid/video"
      - "./work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    network_mode: bridge

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./work/jenkins:/var/jenkins_home
    ports:
      - 8000:8080
    network_mode: bridge

  jira:
    image: atlassian/jira-software
    volumes:
      - "./work/jira:/var/atlassian/application-data/jira"
    ports:
      - "9999:8080"
    network_mode: bridge
