version: '3.8'

services:
  selenoid:
    container_name: selenoid-test
    image: aerokube/selenoid
    volumes:
      - "./config:/etc/selenoid"
      - "./work/selenoid/video:/opt/selenoid/video"
      - "./work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    network_mode: bridge

  selenoid-ui:
    container_name: selenoid-ui-test
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: dockerfile_applecomru_ui_tests
    volumes:
      - "./allure_results:/applecomru_ui_tests/allure_results"
      - "./screenshots:/applecomru_ui_tests/screenshots"
    network_mode: host

